#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FormatType {
    DepthComponent,
    Rgba,
    Rgb,
    Bgr,
    Bgra,
    R3G3B2,
    Rgb4,
    Rgb5,
    Rgb8,
    Rgb10,
    Rgb12,
    Rgb16,
    Rgba2,
    Rgba4,
    Rgb5A1,
    Rgba8,
    Rgb10A2,
    Rgba12,
    Rgba16,
    R16F,
    Rgba32F,
    Rgba16F,
    Rgb32F,
    Rgb16F,
    Red,
    Green,
    Blue,
    Alpha,
    Srgb,
    Srgb8,
    SrgbAlpha,
    Srgb8Alpha8,
    DepthComponent16,
    DepthComponent24,
    DepthComponent32,
}

impl FormatType {
    pub fn get(&self) -> u32 {
        self.value()
    }

    pub fn value(&self) -> u32 {
        use gl::*;
        match self {
            FormatType::DepthComponent => DEPTH_COMPONENT,
            FormatType::Rgba => RGBA,
            FormatType::Rgb => RGB,
            FormatType::Bgr => BGR,
            FormatType::Bgra => BGRA,
            FormatType::R3G3B2 => R3_G3_B2,
            FormatType::Rgb4 => RGB4,
            FormatType::Rgb5 => RGB5,
            FormatType::Rgb8 => RGB8,
            FormatType::Rgb10 => RGB10,
            FormatType::Rgb12 => RGB12,
            FormatType::Rgb16 => RGB16,
            FormatType::Rgba2 => RGBA2,
            FormatType::Rgba4 => RGBA4,
            FormatType::Rgb5A1 => RGB5_A1,
            FormatType::Rgba8 => RGBA8,
            FormatType::Rgb10A2 => RGB10_A2,
            FormatType::Rgba12 => RGBA12,
            FormatType::Rgba16 => RGBA16,
            FormatType::R16F => R16F,
            FormatType::Rgba32F => RGBA32F,
            FormatType::Rgba16F => RGBA16F,
            FormatType::Rgb32F => RGB32F,
            FormatType::Rgb16F => RGB16F,
            FormatType::Red => RED,
            FormatType::Green => GREEN,
            FormatType::Blue => BLUE,
            FormatType::Alpha => ALPHA,
            FormatType::Srgb => SRGB,
            FormatType::Srgb8 => SRGB8,
            FormatType::SrgbAlpha => SRGB_ALPHA,
            FormatType::Srgb8Alpha8 => SRGB8_ALPHA8,
            FormatType::DepthComponent16 => DEPTH_COMPONENT16,
            FormatType::DepthComponent24 => DEPTH_COMPONENT24,
            FormatType::DepthComponent32 => DEPTH_COMPONENT32,
        }
    }
}
