stages:
  - build

variables:
  CARGO_TERM_COLOR: always

linux_release:
  stage: build
  image: rust:latest
  script:
    - apt-get update && apt-get install -y --no-install-recommends ca-certificates build-essential cmake clang libclang-dev
    - make linux-build-release
  artifacts:
    name: "linux-desktop-release"
    paths:
      - target/release/examples/desktop
    expire_in: 1 week
  only:
    - branches
    - tags
    - merge_requests

android_apk:
  stage: build
  image: rust:latest
  before_script:
    - apt-get update
    - apt-get install -y --no-install-recommends curl unzip openjdk-21-jdk-headless ca-certificates pkg-config libssl-dev build-essential cmake clang libclang-dev
  script:
    - make setup-android
    - echo "$ANDROID_KEYSTORE_B64" | base64 -d > release.keystore
    - make android-apk
    - make android-apk-release
  artifacts:
    name: "android-apks"
    paths:
    - target/debug/apk/**/*.apk
    - target/release/apk/**/*.apk
    expire_in: 1 week
  only:
    - branches
    - tags
    - merge_requests

